name: python-infographics

channels:
  - esri
  - conda-forge

dependencies:
  - appnope
  - arcgis
  - black>=21
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pandoc
  - pip
  - pytest
  - tqdm
  - pip:
    - autodocsumm
    - build
    - bump2version
    - furo
    - nbsphinx
    - sphinx
    - sphinxcontrib-youtube
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - streamlit
    - twine
